// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-w5bD74Eg4mi5q529I1GYX__YXuB8AA',
    appId: '1:845305226005:web:26d5413eefbc703e3fbf1c',
    messagingSenderId: '845305226005',
    projectId: 'e-czane-notifier',
    authDomain: 'e-czane-notifier.firebaseapp.com',
    storageBucket: 'e-czane-notifier.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiQQRBLclbjwd_eJFCHqyifKsAE5FOWE0',
    appId: '1:845305226005:android:666825ee4a019eee3fbf1c',
    messagingSenderId: '845305226005',
    projectId: 'e-czane-notifier',
    storageBucket: 'e-czane-notifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd28YGZ6qAQFB2cKAXO7gwMyo25oiJWC4',
    appId: '1:845305226005:ios:5b2ab9d7f6defe213fbf1c',
    messagingSenderId: '845305226005',
    projectId: 'e-czane-notifier',
    storageBucket: 'e-czane-notifier.appspot.com',
    iosBundleId: 'com.example.eCzane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd28YGZ6qAQFB2cKAXO7gwMyo25oiJWC4',
    appId: '1:845305226005:ios:5b2ab9d7f6defe213fbf1c',
    messagingSenderId: '845305226005',
    projectId: 'e-czane-notifier',
    storageBucket: 'e-czane-notifier.appspot.com',
    iosBundleId: 'com.example.eCzane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ-w5bD74Eg4mi5q529I1GYX__YXuB8AA',
    appId: '1:845305226005:web:62b64f6d715196403fbf1c',
    messagingSenderId: '845305226005',
    projectId: 'e-czane-notifier',
    authDomain: 'e-czane-notifier.firebaseapp.com',
    storageBucket: 'e-czane-notifier.appspot.com',
  );
}
